Repository Saurav-Pant/Blood-Donation-Project, pull requests merged in 2024-07, with the labels that each got.

#197 Fixes issue #159
  .github/workflows/issue-created.yml
  .github/workflows/pull_request_created.yml
Labels: GSSoC'24, priority: high, level2

#201 added circle for donate blood title
  src/components/Hero.tsx
Labels: GSSoC'24, level2

#224 footer_updated
  src/components/Footer.tsx
Labels: GSSoC'24, level2

#237 reduced size of Dockerfile
  .dockerignore
  Dockerfile
Labels: GSSoC'24, level3

#240 Update contributing.md for running docker container
  contributing.md
Labels: GSSoC'24, level2

#252 add-dockerignore-file
  .dockerignore
Labels: GSSoC'24, level2

#259 Create LICENSE
  LICENSE
Labels: GSSoC'24, level2

#262 feat: Added mail option in footer
  src/components/Footer.tsx
Labels: GSSoC'24, level2

#263 [Feature] : Singin & signup theme adoption
  src/app/globals.css
  src/app/sign-in/[[...sign-in]]/page.tsx
  src/app/sign-up/[[...sign-up]]/page.tsx
Labels: GSSoC'24, level2

#266 Regarding issue#265 Dockerfile optimization
  Dockerfile
Labels: GSSoC'24, priority: high, level3
